// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_stock.sql

package database

import (
	"context"
)

const createStockItem = `-- name: CreateStockItem :one
INSERT INTO stock (id, stockname, amount, qty_type, price_per)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, stockname, amount, qty_type, price_per
`

type CreateStockItemParams struct {
	Stockname string
	Amount    int32
	QtyType   string
	PricePer  float64
}

func (q *Queries) CreateStockItem(ctx context.Context, arg CreateStockItemParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, createStockItem,
		arg.Stockname,
		arg.Amount,
		arg.QtyType,
		arg.PricePer,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Stockname,
		&i.Amount,
		&i.QtyType,
		&i.PricePer,
	)
	return i, err
}
