// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_user.sql

package database

import (
	"context"
)

const createNewUser = `-- name: CreateNewUser :one
INSERT INTO users (id, user_name, pass_word)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, user_name, pass_word
`

type CreateNewUserParams struct {
	UserName string
	PassWord string
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createNewUser, arg.UserName, arg.PassWord)
	var i User
	err := row.Scan(&i.ID, &i.UserName, &i.PassWord)
	return i, err
}
