// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_to_invoice.sql

package database

import (
	"context"
)

const addToInvoice = `-- name: AddToInvoice :one
INSERT INTO invoice (id, user_name, stockname, amount, qty_type, price_per, total_price, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW()
)
RETURNING id, user_name, stockname, amount, qty_type, price_per, total_price, created_at
`

type AddToInvoiceParams struct {
	UserName   string
	Stockname  string
	Amount     int32
	QtyType    string
	PricePer   float64
	TotalPrice float64
}

func (q *Queries) AddToInvoice(ctx context.Context, arg AddToInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, addToInvoice,
		arg.UserName,
		arg.Stockname,
		arg.Amount,
		arg.QtyType,
		arg.PricePer,
		arg.TotalPrice,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Stockname,
		&i.Amount,
		&i.QtyType,
		&i.PricePer,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}
