// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: adjust_stock_amount.sql

package database

import (
	"context"
)

const adjustStockAmount = `-- name: AdjustStockAmount :exec

UPDATE stock
SET amount = amount + $1
WHERE stockname = $2
`

type AdjustStockAmountParams struct {
	Amount    int32
	Stockname string
}

func (q *Queries) AdjustStockAmount(ctx context.Context, arg AdjustStockAmountParams) error {
	_, err := q.db.ExecContext(ctx, adjustStockAmount, arg.Amount, arg.Stockname)
	return err
}
