// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: check_password.sql

package database

import (
	"context"
)

const getPassword = `-- name: GetPassword :one

SELECT  pass_word FROM users
WHERE user_name = $1
`

func (q *Queries) GetPassword(ctx context.Context, userName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassword, userName)
	var pass_word string
	err := row.Scan(&pass_word)
	return pass_word, err
}
