// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: log_history.sql

package database

import (
	"context"
)

const logHistory = `-- name: LogHistory :exec

INSERT INTO history(id, user_name, stockname, edit_time, adjustment)
VALUES(gen_random_uuid(), $1, $2, NOW(), $3)
`

type LogHistoryParams struct {
	UserName   string
	Stockname  string
	Adjustment string
}

func (q *Queries) LogHistory(ctx context.Context, arg LogHistoryParams) error {
	_, err := q.db.ExecContext(ctx, logHistory, arg.UserName, arg.Stockname, arg.Adjustment)
	return err
}
