// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type History struct {
	ID         uuid.UUID
	UserName   string
	Stockname  string
	EditTime   time.Time
	Adjustment string
}

type Stock struct {
	ID        uuid.UUID
	Stockname string
	Amount    int32
	QtyType   string
	PricePer  int32
}

type User struct {
	ID       uuid.UUID
	UserName string
	PassWord string
}
