// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
)

type Stock struct {
	ID        uuid.UUID
	Stockname string
	Amount    int32
	QtyType   string
	PricePer  int32
}
