// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: show_all_stock.sql

package database

import (
	"context"
)

const showAllStock = `-- name: ShowAllStock :many

SELECT  id, stockname, amount, qty_type, price_per FROM stock
`

func (q *Queries) ShowAllStock(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, showAllStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Stockname,
			&i.Amount,
			&i.QtyType,
			&i.PricePer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
