// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_history.sql

package database

import (
	"context"
)

const showStockHistory = `-- name: ShowStockHistory :many

SELECT  TO_CHAR(edit_time, 'DD-MM-YYYY HH24:MI:SS'), user_name, adjustment FROM history
WHERE stockname = $1
ORDER BY edit_time DESC
`

type ShowStockHistoryRow struct {
	ToChar     string
	UserName   string
	Adjustment string
}

func (q *Queries) ShowStockHistory(ctx context.Context, stockname string) ([]ShowStockHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, showStockHistory, stockname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowStockHistoryRow
	for rows.Next() {
		var i ShowStockHistoryRow
		if err := rows.Scan(&i.ToChar, &i.UserName, &i.Adjustment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
